Files added from local repository
Ayush-kumar1/Social-media-submission-frontend pull request #1
Opened 2021-06-24 13:31 UTC by Ayush-kumar1

Review the code for the frontend of Social media app

2021-07-07 05:29 UTC, rohiraanjali commented on src/App.js
> +import './App.css';
Use index.js for each folder to export (Avoid repeating names on the imports) and imports from similar index.js file in one line→ clean code

2021-07-07 05:42 UTC, rohiraanjali commented
- Customise the `favicon` and title in your App.

What to do → Generate your own favicon and app-icons using an online Favicon Generator, like (https://www.favicon-generator.org/).

Replace the **`favicon.ico`**, **`logo192.png`**, and **`logo512.png`** in the public directory with your own generated files



- *Do not leave it as → default title. I personally believe it shows that you are really interested in what you are doing and → others can see that in your app, instead of React logo and default `title.Example`*

what to do → Change the title of your website, as per your wishes, preferably the name of the website.

Change the content in the **`meta-description`** tag, to something that describes the website well, which might also help in `Search Engine Optimization`.

2021-07-07 07:22 UTC, rohiraanjali reviewed
The App looks good, Done code review. Please check and make changes accordingly.

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Login/Login.jsx
> +import React, { useState } from "react";
make all imports in one line as commented for App.js

2021-07-07 07:22 UTC, rohiraanjali commented on src/App.js
> +import './App.css';
Use index.js for each folder to export (Avoid repeating names on the imports) and imports from similar index.js file in one line→ clean code

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Login/Login.jsx
> +      fetch("https://chit-chat-12.herokuapp.com/signin", {
Create a `.env.local` file, at the root of your project, and put all your secrets there like this.


`REACT_APP_SECRET_NAME= 'theValueOfYourSecret'
`

→ And to access it in your code, you can use `process.env.REACT_APP_SECRET_NAME`

`const mySecret = process.env.REACT_APP_SECRET_NAME`

Include the `.env.local` file to your `.gitignore`, if it isn't already.

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Login/Login.jsx
> +              <h5 className="signup-redirect" style={{ color: "black" }}>
Avoid using style in jsx. Use classNames for the same and add all your styling to CSS

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Profile/Profile.jsx
> +        fetch("https://chit-chat-12.herokuapp.com/mypost",{
Hide this SECRET_KEY as commented on Login.jsx

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Profile/Profile.jsx
> +          console.log(data)
Remove the unnecessary console.logs

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Profile/Profile.jsx
> +        <div style={{paddingTop:"7rem"}}>
Move all the styling to CSS through classNames

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Subscribepost/Subscribepost.jsx
> +              <div className="media-card">
Make classNames naming consistent. either use hyphens(-) for all or underscore(_) for all or just camelCase. Make consistency through out your codebase by using one style of naming

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Subscribepost/Subscribepost.jsx
> +export default Subscribepost;
use camelCase for function names al over your codebase

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Userprofile/Userprofile.css
> +.img {
Don't use .img as classNames. Give names for the usage of image. Like if its postImage, give classNames around what it does

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Userprofile/Userprofile.jsx
> +  const follow = () => {
It is advisable to use descriptive functions/ component names so that it increases the code readability. Now, I am not able to understand what "follow" function does unless I read the whole of the code. Instead make it "followUser" or something which describe its usage well

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Userprofile/Userprofile.jsx
> +  const unfollow = () => {
Change naming for this as well. as mentioned previously for follow

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Userprofile/Userprofile.jsx
> +                    <img className="img" src={elem.photo} alt="Gallery pics" />
Descriptive classNames are required

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/CreatePost/CreatePost.jsx
> +        // console.log(data)
check the files and remove all the commented-out code and console. logs.

2021-07-07 07:22 UTC, rohiraanjali commented on README.md
> +# Getting Started with Create React App
update Readme.md file -> It helps others understand its use, it's working, and the technologies it uses

Things to include in Readme:-
- Name, Description of your project.
- Tech stack used.
- Features of your application.
- Live link.
- Screenshots and Videos to explain the working of the application.
- Test credentials for users.
- Instructions for running the app in the local environment.

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Home/Home.jsx
> +        {data &&
specify what data it is.. what is its use? Is it userData? or postsData? what it is? mention!!

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/Header/Header.jsx
> +  function nav() {
use camelCase for function names, as you have done in other functions -> Make consistency

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/CreatePost/CreatePost.jsx
> +  const [image, setImage] = useState("");
make it postImage insted of just image

2021-07-07 07:22 UTC, rohiraanjali commented on src/components/CreatePost/CreatePost.jsx
> +export default CreatePost;
function names to be camelCase. whatever you use make sure it's same through out your application code. so change it either wise but make it consistent

2021-07-07 07:22 UTC, rohiraanjali commented on src/App.css
> +    margin: 0;
Remove unwanted and useless files like App.css, index.css for clean structure

2021-07-07 09:48 UTC, ardourApeX commented on src/components/Login/Login.jsx
> +      !/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
Regex Expression can be placed inside in a separate folder and could be named Constants for better code management and readability.

2021-07-07 09:51 UTC, ardourApeX commented on src/components/Login/Login.jsx
> +      fetch("https://chit-chat-12.herokuapp.com/signin", {
Suggestion: Better if you could use Axios over fetch

2021-07-07 09:52 UTC, ardourApeX commented on src/components/Login/Login.jsx
> +          if (data.message !== "Login succesful") {
Instead of checking over messages, you can use status or success.

2021-07-07 09:54 UTC, ardourApeX commented on src/components/Login/Login.jsx
> +
Even after logging in, the user can still access the login route which makes no sense, better to navigate it to some other route.

2021-07-07 09:56 UTC, ardourApeX commented on src/components/Login/Login.jsx
> +            onClick={() => postData()}
I can make multiple login requests at a time by rapidly clicking on the Login button.

2021-07-07 10:10 UTC, ardourApeX commented on src/components/Home/Home.jsx
> +                      <ThumbUpIcon onClick={() => postLikes(elem._id)} />
I can increase the number of likes by more than 1 by rapidly clicking over the like button. Ideally I should be able to increase likes by 1 only.

2021-07-07 10:15 UTC, ardourApeX commented on src/components/Home/Home.jsx
> +                        onClick={() => deletePost(elem._id)}
This button sometimes works and sometimes not. I tried deleting the post 4-5 times and at the 6th time, it finally gets deleted.

2021-07-07 10:27 UTC, ardourApeX commented on src/components/Signup/Signup.jsx
> +
Logged in users can still access signup route

2021-07-07 10:28 UTC, ardourApeX commented on src/components/Signup/Signup.jsx
> +    fetch("	https://api.cloudinary.com/v1_1/ayush5555/image/upload", {
would be better if you could use axios over fetch

2021-07-07 10:37 UTC, ardourApeX commented on src/components/Subscribepost/Subscribepost.jsx
> +                          {item.postedBy.name}-
This route is not getting rendered.
It raises an error.
![image](https://user-images.githubusercontent.com/56365512/124745428-7098e700-df3d-11eb-821b-39bde4d78045.png)

2021-07-07 10:39 UTC, ardourApeX requested changes
Version 1 of social media is quite good.

2021-07-07 10:40 UTC, ardourApeX commented
On refreshing 

> Version 1 of social media is quite good.

One issue is that, if I refresh any page the link gets broken.
![image](https://user-images.githubusercontent.com/56365512/124745862-e309c700-df3d-11eb-83a1-5be782c91978.png)

2021-07-09 14:28 UTC, thesudeshdas requested changes

2021-07-09 14:28 UTC, thesudeshdas commented on src/App.js
> +import './App.css';
Use a code formatter

2021-07-09 14:28 UTC, thesudeshdas commented on src/components/CreatePost/CreatePost.css
> +.media_card {
object-fit: cover in images

2021-07-09 14:28 UTC, thesudeshdas commented on src/App.js
> +
Add a star route

2021-07-10 14:46 UTC, merged